### Stacking

Stacking van arrays betekent dat we de een 'bovenop' de ander plaatsen, of naast elkaar plaatsen.  We kunnen zowel verticaal als horizontaal stacken.

Natuurlijk moeten de stacks compatibel zijn.  
Voor verticaal stapelen moet elke array hetzelfde aantal kolommen hebben.  
Voor horizontaal stapelen (naast elkaar), moet elke array hetzelfde aantal rijen hebben.

In [1]:
import numpy as np

In [2]:
a1 = np.arange(1, 6)
a1

array([1, 2, 3, 4, 5])

In [3]:
a2 = np.arange(1, 11).reshape(2, 5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
s1 = np.vstack((a1, a2))
s1

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Als we proberen om twee arrays die een verschillend aantal kolommen hebben proberen te vstack 'en, krijgen we een error: 

In [5]:
try:
    np.vstack((np.arange(3), a2))
except ValueError as ex:
    print(ex)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5


Wanneer we arrays stacken, wat gebeurt er met het data type? 

NumPy zal het datatype aanpassen om het ruimste te gebruiken dat nodig is om alle elementen in een enkele array op te slaan.

Bijvoorbeeld, wanneer we een array van integers en een array van floats stacken, dan krijgen we een array van floats:

In [6]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([0.1, 0.2, 0.3, 0.4])
result = np.vstack((a1, a2))
result

array([[1. , 2. , 3. , 4. ],
       [0.1, 0.2, 0.3, 0.4]])

In [7]:
result.dtype

dtype('float64')

We kunnen ook twee arrays hebben die verschillende integer types hebben:

In [8]:
a1 = np.array([1, 2, 3, 4], dtype=np.uint8)
a2 = np.array([1000, 2000, 3000, 4000], dtype=np.uint16)
result = np.vstack((a1, a2))
result

array([[   1,    2,    3,    4],
       [1000, 2000, 3000, 4000]], dtype=uint16)

Zoals je kan zien, kiest NumPy het ruimste data type wat nodig is om deze stack te kunnen uitvoeren.

We kunnen ook meer dan twee arrays stacken, en ook in dit geval zal NumPy het data type aanpassen indien nodig:

In [9]:
np.vstack(
    (
        np.arange(5), 
        np.linspace(0, 1, 5),
        np.eye(5)
    )
)

array([[0.  , 1.  , 2.  , 3.  , 4.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  ]])

Merk op dat het resulterend data type niet noodzakelijk overeenkomt met dat van één van de individuele arrays:

In [10]:
a1 = np.array([1, 2], dtype=np.uint8)
a2 = np.array([2, 3], dtype=np.uint64)
a3 = np.array([4, 5], dtype=np.int32)

result = np.vstack([a1, a2, a3])
result

array([[1., 2.],
       [2., 3.],
       [4., 5.]])

In [11]:
result.dtype

dtype('float64')

Zoals je kan zien, kiest NumPy `float64`.

Indien je dit wenst te controleren, zal je arrays die hetzelfde `dtype` hebben moeten kiezen.

We kunnen op eenvoudige manier een array van het ene naar het andere datatype converteren met behulp van de `astype` methode:

In [12]:
a1

array([1, 2], dtype=uint8)

In [13]:
a1.astype(np.float32)

array([1., 2.], dtype=float32)

We kunnen dit gebruiken wanneer we de arrays 'stapelen' of 'stacken'. Natuurlijk moeten we voorzichtig zijn om een datatype te kiezen dat niet zal resulteren in dataverlies.

In [14]:
result = np.vstack(
    (
        a1.astype(np.int64), 
        a2.astype(np.int64),
        a3.astype(np.int64)
    )
)
result

array([[1, 2],
       [2, 3],
       [4, 5]])

In [15]:
result.dtype

dtype('int64')

**BELANGRIJK**

In tegenstelling tot reshaped arrays, delen stacked arrays hun elementen **niet** met de originele arrays!

In [16]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([10, 20, 30, 40])
result = np.vstack((a1, a2))
result

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [17]:
a1[0] = 100
a1

array([100,   2,   3,   4])

In [18]:
result

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [19]:
result[1, 0] = -10
result

array([[  1,   2,   3,   4],
       [-10,  20,  30,  40]])

In [20]:
a2

array([10, 20, 30, 40])

Zoals we kunnen zien, beïnvloedt het wijzigen van de originele array de stacked array **niet**, en het wijzigen van de stacked array beïnvloedt de originele array **niet**.

De `hstack` methode werkt op gelijkaardige manier, maar dan met 'zijdelings' stacken - naast elkaar!

In [21]:
a1 = np.linspace(0, 5, 10).reshape(5, 2)
a1

array([[0.        , 0.55555556],
       [1.11111111, 1.66666667],
       [2.22222222, 2.77777778],
       [3.33333333, 3.88888889],
       [4.44444444, 5.        ]])

In [22]:
np.random.seed(0)
a2 = np.random.randint(0, 10, 10).reshape(5, 2)
a2

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4]])

In [23]:
result = np.hstack((a1, a2))
result

array([[0.        , 0.55555556, 5.        , 0.        ],
       [1.11111111, 1.66666667, 3.        , 3.        ],
       [2.22222222, 2.77777778, 7.        , 9.        ],
       [3.33333333, 3.88888889, 3.        , 5.        ],
       [4.44444444, 5.        , 2.        , 4.        ]])