### Slicing

Slicing van 1D arrays werkt net zoals dit bij Python sequences het geval is.

In [1]:
l = [1, 2, 3, 4, 5, 6]

In [2]:
l[-2::-2]

[5, 3, 1]

In [3]:
l[0:3]

[1, 2, 3]

In [4]:
l[0::2]

[1, 3, 5]

In [5]:
l[::-1]

[6, 5, 4, 3, 2, 1]

In [6]:
import numpy as np

In [7]:
arr = np.array(l)

In [41]:
arr.dtype

dtype('int64')

In [8]:
arr[0:3]

array([1, 2, 3])

In [9]:
arr[0::2]

array([1, 3, 5])

In [10]:
arr[::-1]

array([6, 5, 4, 3, 2, 1])

Er is echter één **fundamenteel** verschil tussen het slicen van Python sequences en het slicen van NumPy-arrays.

In Python is de slice volledig onafhankelijk van de oorspronkelijke lijst:

In [11]:
l

[1, 2, 3, 4, 5, 6]

In [12]:
slice_ = l[0:2]
slice_

[1, 2]

In [13]:
slice_[0] = 100
slice_

[100, 2]

In [14]:
l

[1, 2, 3, 4, 5, 6]

Zoals je kan zien hebben we de slice aangepast, maar heeft dit geen impact op de originele lijst.

Laten we nu even zien wat er gebeurt met NumPy slicing:

In [15]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [16]:
slice_ = arr[0:2]
slice_

array([1, 2])

In [17]:
slice_[0] = 100
slice_

array([100,   2])

Dus de slice is aangepast, en de originele array...

In [18]:
arr

array([100,   2,   3,   4,   5,   6])

ook gewijzigd!

Het omgekeerde geldt ook; indien de originele array wordt gewijzigd:

In [19]:
arr = np.arange(1, 7)
slice_ = arr[3:]
slice_

array([4, 5, 6])

In [20]:
arr[-1] = 60
arr

array([ 1,  2,  3,  4,  5, 60])

In [21]:
slice_

array([ 4,  5, 60])

En zoals we kunnen zien is de slice ook gewijzigd:

Indien we deze 'link' willen verbreken, kunnen we gewoonweg een kopie van de slice maken:

In [22]:
arr = np.arange(1, 7)
slice_ = arr[3:].copy()
slice_

array([4, 5, 6])

In [23]:
slice_[-1] = 60
slice_

array([ 4,  5, 60])

In [24]:
arr

array([1, 2, 3, 4, 5, 6])

#### 2-D Arrays

2-D arrays zijn iets moeilijker te slicen, maar we gaan enkele verschillende manieren proberen.

Laten we starten met een vierkante 5 x 5 array van integers van 1 tot 25:

In [2]:
import numpy as np
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Stel dat we de volgende elementen wensen te selecteren:
```
1 2
6 7
```

Dit komt overeen met het kijken naar de eerste twee elementen van de eerste twee rijden van `arr`.

Dit betekent dat we de eerste twee rijen in de eerste as (dimensie) moeten slicen, en de eerste twee elementen in de tweede as (dimensie):

In [26]:
arr[0:2, 0:2]

array([[1, 2],
       [6, 7]])

Dit kan vreemder worden wanneer we met stappen werken.  Stel dat we de volgende elementen van de array wensen: 
```
1  3   5
11 13  15
21 23  25
```

Zoals we kunnen zien, kiezen we elke tweede rij (beginnend bij rij 0) en elke tweede kolom (beginnend bij kolom 0), dus we kunnen de slices in beide assen combineren:

In [27]:
arr[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

We kunnen ook indexing langs één as combineren met slicing in een andere as.

We kunnen bijvoorbeeld elk tweede element selecteren, startend bij het tweede element, in de derde rij:

In [28]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
arr[2, 1::2]

array([12, 14])

Opnieuw, bedenk dat de slice gekoppeld blijft met de originele array:

In [30]:
slice_ = arr[2, 1::2]
slice_

array([12, 14])

In [31]:
slice_[0] = 120
slice_

array([120,  14])

In [32]:
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11, 120,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

Een vraag die je je waarschijnlijk stelt, is hoe selecteer ik een slice van de eerste, tweede en vierde rijen? Je kunt geen slice met een stap gebruiken om de rijen te selecteren - een slice kan niet de rijen 0, 1, 2 slicen, dus wat is de oplossing?

We zien dit binnenkort: *fancy indexing*.

#### Toewijzen van waarden aan Slices

We kunnen meerdere elementen in een Python-lijst vervangen door een sequentie toe te wijzen aan een slice:

In [33]:
l = [1, 2, 3, 4, 5, 6]

In [34]:
l[0:3] = [10, 20, 30]
l

[10, 20, 30, 4, 5, 6]

We zagen zelfs dat we het aantal elementen dat we vervangen kunnen veranderen - dit is mogelijk omdat Python-lijsten, in tegenstelling tot NumPy-arrays, geen vaste grootte hebben.

In [35]:
l = [1, 2, 3, 4, 5, 6]
l[0:3] = [10, 20, 30, 40, 50]
l

[10, 20, 30, 40, 50, 4, 5, 6]

We kunnen iets gelijkaardig doen met NumPy arrays, maar natuurlijk kunnen we de grootte van de originele array niet wijzigen.

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[0:3] = np.array([10, 20, 30])
arr

array([10, 20, 30,  4,  5,  6])

We kunnen zelfs een list in plaats van een `ndarray` gebruiken:

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[::2] = [10, 30, 50]
arr

array([10,  2, 30,  4, 50,  6])

We kunnen natuurlijk geen toewijzing doen die de grootte van de array zou wijzigen:

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[0:3] = [10, 20, 30, 40]

ValueError: could not broadcast input array from shape (4,) into shape (3,)

We kunnen echter een **enkele waarde** toewijzen aan een slice - NumPy zal die waarde gewoon zo vaak herhalen als nodig is om elk element van de slice te vervangen door die waarde.

In [24]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
arr[::2, ::2]

array([[0, 2],
       [6, 8]])

In [26]:
arr[::2, ::2] = 100
arr

array([[100,   1, 100],
       [  3,   4,   5],
       [100,   7, 100]])

Nog iets om op te merken is dat hoewel een ndarray slice "gelinkt" is aan de originele array, als we het vervangen door een andere array, dan is die vervangen slice niet gelinkt aan die tweede array.

Laten we een voorbeeld zien om dit te illustreren:

In [27]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20])

In [28]:
arr1[0:2] = arr2
arr1

array([10, 20,  3,  4,  5])

In [29]:
arr2[0] = 100
arr2

array([100,  20])

In [30]:
arr1

array([10, 20,  3,  4,  5])

Natuurlijk werkt deze toewijzing aan slices ook in hogere dimensies, we moeten er alleen voor zorgen dat we een array (of lijst van lijsten) toewijzen die dezelfde vorm heeft als de slice.

In [31]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr[:2, 1:]

array([[1, 2],
       [4, 5]])

In [33]:
arr[:2, 1:] = [[10, 20], [40, 50]]
arr

array([[ 0, 10, 20],
       [ 3, 40, 50],
       [ 6,  7,  8]])

En als we proberen een array toe te wijzen die niet dezelfde vorm heeft, krijgen we een fout, zelfs als het totale aantal elementen overeenkomt met het totale aantal elementen in de slice:

In [34]:
arr[:2, 1:] = [10, 20, 40, 50]

ValueError: could not broadcast input array from shape (4,) into shape (2,2)

Natuurlijk kan je altijd een reshape doen voor de toewijzing:

In [ ]:
arr[:2, 1:] = np.array([10, 20, 40, 50]).reshape(2, 2)
arr

Tot slot: aangezien NumPy arrays een vast homogeen `dtype` hebben, moeten we voorzichtig zijn bij het mixen van types. Stel dat we een array van unsigned 8-bit integers hebben (range `[0, 255]`):

In [ ]:
arr = np.array([10, 20, 30, 40, 50], dtype=np.uint8)

In [ ]:
arr

In [ ]:
arr[0:2] = [-100, 300]
arr

Zoals je opmerkt "wrappen" de integers weer zoals voorheen gezien.