### Arrays "van Scratch" maken

In [1]:
import numpy as np

We kunnen ook `ndarray` objecten maken met behulp van ingebouwde NumPy functies.

#### zeros

De `np.zeros` functie wordt gebruikt om arrays te maken die enkel uit nullen bestaan.

In [2]:
a = np.zeros(5)

In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
a.dtype

dtype('float64')

Het standaard data `dtype` is `float64`, maar we kunnen iets anders opgeven als argument:

In [5]:
a = np.zeros(5, dtype=int)

In [6]:
a

array([0, 0, 0, 0, 0])

In [7]:
a.dtype

dtype('int64')

Je zult opmerken hoe ik het Python `int` object gebruik om het gegevenstype voor `dtype` te specificeren - dit werkt omdat NumPy het corresponderende C-type kiest dat het best compatibel is met het Python gegevenstype. (Python `float` zal resulteren in het gebruik van `dtype.float64`).

Dit betekent dat we zowel de lengte als het data type van de 1-D array kunnen bepalen.  

We kunnen ook een shape aangeven om een multi-dimensionale array te maken:

In [8]:
m = np.zeros((4, 3), dtype=np.uint8)

In [9]:
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [10]:
m.shape

(4, 3)

#### ones

De `np.ones` functie werkt net als `np.zeros` maar zal de array populeren met `1`s.

In [11]:
m = np.ones((10, 2), dtype=float)

In [12]:
m

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
m.dtype

dtype('float64')

#### full

De `np.full` functie is een meer generieke variant van `np.zeros` en `np.ones` waar we zelf kunnen kiezen met welke waarde we de array wensen te populeren.

In [14]:
m = np.full((2, 5), 3.14)

In [15]:
m

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

#### identiteitsmatrix

NumPy maakt het heel eenvoudig om een identiteitsmatrix te maken met de functie `np.eye`.

In [16]:
m = np.eye(5)
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
m.dtype

dtype('float64')

Zoals gewoonlijk kunnen we hier een `dtype` specifiëren indien we dit wensen:

In [18]:
m = np.eye(4, dtype=int)

In [19]:
m

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
m.dtype

dtype('int64')

We kunnen een niet-vierkante matrix creëren, maar deze functie verwacht dat het aantal rijen en het aantal kolommen afzonderlijk worden doorgegeven als positionele argumenten, niet als een tuple die de vorm bepaalt. Standaard gaat het ervan uit dat het aantal kolommen hetzelfde is als het aantal rijen.

In [21]:
np.eye(5, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### op bereik gebaseerd

In **Python** kunnen we een lijst maken gebaseerd op een range object:

In [1]:
list(range(2, 11, 2))

[2, 4, 6, 8, 10]

**NumPy** voorziet gelijkaardige functionaliteit via de `np.arange` functie.

In [4]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

Zoals gebruikelijk kunnen we het data type van de elementen bepalen:

In [24]:
np.arange(2, 11, 2, dtype=np.uint8)

array([ 2,  4,  6,  8, 10], dtype=uint8)

#### linspace

`linspace` (linear space) stelt ons in staat een gespecificeerd aantal gelijkmatig verdeelde waarden te creëren tussen twee (inclusieve) waarden. Dit kan zeer nuttig zijn voor het genereren van 1-D arrays die een bepaalde as voorstellen (zoals een x-as of een tijdas).

In [25]:
import numpy as np
np.linspace(2, 10, num=5)

array([ 2.,  4.,  6.,  8., 10.])

In [26]:
np.linspace(2, 10, 10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

We willen bijvoorbeeld data genereren om een functie te plotten:

Stel dat de data willen genereren voor de functie `x --> sin(x)`.  We kunnen starten met het maken van een linspace van gelijkmatig verdeelde waarden tussen `-2pi` en `2pi`:

In [27]:
import math

x_coords = np.linspace(-2 * math.pi, 2 * math.pi, 50)

In [28]:
x_coords

array([-6.28318531, -6.02672876, -5.77027222, -5.51381568, -5.25735913,
       -5.00090259, -4.74444605, -4.48798951, -4.23153296, -3.97507642,
       -3.71861988, -3.46216333, -3.20570679, -2.94925025, -2.6927937 ,
       -2.43633716, -2.17988062, -1.92342407, -1.66696753, -1.41051099,
       -1.15405444, -0.8975979 , -0.64114136, -0.38468481, -0.12822827,
        0.12822827,  0.38468481,  0.64114136,  0.8975979 ,  1.15405444,
        1.41051099,  1.66696753,  1.92342407,  2.17988062,  2.43633716,
        2.6927937 ,  2.94925025,  3.20570679,  3.46216333,  3.71861988,
        3.97507642,  4.23153296,  4.48798951,  4.74444605,  5.00090259,
        5.25735913,  5.51381568,  5.77027222,  6.02672876,  6.28318531])

En nu kunnen we een lijst maken met de functiewaarden bij elk van deze x coördinaten:

In [29]:
y_values = np.array([math.sin(x) for x in x_coords])

In [30]:
y_values

array([ 2.44929360e-16,  2.53654584e-01,  4.90717552e-01,  6.95682551e-01,
        8.55142763e-01,  9.58667853e-01,  9.99486216e-01,  9.74927912e-01,
        8.86599306e-01,  7.40277997e-01,  5.45534901e-01,  3.15108218e-01,
        6.40702200e-02, -1.91158629e-01, -4.33883739e-01, -6.48228395e-01,
       -8.20172255e-01, -9.38468422e-01, -9.95379113e-01, -9.87181783e-01,
       -9.14412623e-01, -7.81831482e-01, -5.98110530e-01, -3.75267005e-01,
       -1.27877162e-01,  1.27877162e-01,  3.75267005e-01,  5.98110530e-01,
        7.81831482e-01,  9.14412623e-01,  9.87181783e-01,  9.95379113e-01,
        9.38468422e-01,  8.20172255e-01,  6.48228395e-01,  4.33883739e-01,
        1.91158629e-01, -6.40702200e-02, -3.15108218e-01, -5.45534901e-01,
       -7.40277997e-01, -8.86599306e-01, -9.74927912e-01, -9.99486216e-01,
       -9.58667853e-01, -8.55142763e-01, -6.95682551e-01, -4.90717552e-01,
       -2.53654584e-01, -2.44929360e-16])

We zullen later een veel betere manier zien om deze nieuwe array te genereren die het gebruik van op Python gebaseerde berekeningen vermijdt en in plaats daarvan gebruikmaakt van NumPy-vectorisatie.

#### random

We kunnen ook arrays maken die gevuld zijn met willekeurige nummers, zowel floats als integers. Om dit te doen, gebruiken we de `random` module in de NumPy library (niet de `random` module in de standaard Python library!).

In [31]:
np.random.random(5)

array([0.11707888, 0.73623683, 0.17968302, 0.39025525, 0.64846418])

Dit heeft een 1-D array gemaakt met 5 random floats.

Indien we reproduceerbare resultaten wensen kunnen we ook een seed meegeven:

In [32]:
np.random.seed(0)
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [33]:
np.random.seed(0)
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

We kunnen de vorm van de gegenereerde array specificeren door een vormtupel als het eerste argument door te geven:

In [34]:
np.random.random((5, 3))

array([[0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504],
       [0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675, 0.87001215]])

We kunnen ook willekeurige integers genereren in een bepaalde range:

In [35]:
np.random.seed(0)
np.random.randint(1, 10, 5)

array([6, 1, 4, 4, 8])

Dit resulteert in een 1-D array van willekeurige (random) integers tussen `1` en `10` (waarbij `10` niet inclusief is), met als lengte `5`.

We zouden bijvoorbeeld een worp van een dobbelsteen kunnen simuleren, dit 10 keer:

In [9]:
np.random.seed(42)
np.random.randint(1, 6+1, 10)

array([4, 5, 3, 5, 5, 2, 3, 3, 3, 5])

Met behulp van een shape kunnen we het rollen van 2 dobbelstenen simuleren:

In [37]:
np.random.seed(0)
np.random.randint(1, 7, (10, 2))

array([[5, 6],
       [1, 4],
       [4, 4],
       [2, 4],
       [6, 3],
       [5, 1],
       [1, 5],
       [3, 2],
       [1, 2],
       [6, 2]])

of zelfs 5 dobbelstenen - dit blijft gewoon een 2-D array:

In [38]:
np.random.seed(0)
np.random.randint(1, 7, (10, 5))

array([[5, 6, 1, 4, 4],
       [4, 2, 4, 6, 3],
       [5, 1, 1, 5, 3],
       [2, 1, 2, 6, 2],
       [6, 1, 2, 5, 4],
       [1, 4, 6, 1, 3],
       [4, 1, 2, 4, 6],
       [4, 4, 1, 2, 2],
       [2, 1, 3, 5, 4],
       [4, 3, 5, 3, 1]])

We hebben veel manieren gezien om `ndarray`-objecten te creëren:  
Ofwel door het converteren van een Python-list (die bijvoorbeeld uit een CSV-bestand geladen zou kunnen worden), of door ze te genereren met gespecialiseerde `numpy`-functies die we hier hebben gezien. Later zullen we zien hoe we bestaande arrays kunnen transformeren in andere arrays, met behulp van specifieke functies.