### Indexering

We kennen reeds indexering van Python sequence types zoals lijsten en tuples.

In [3]:
a = [1, 2, 3, 4]
a[2]

3

We kunnen zelfs een 2-D list indexeren (een lijst van lijsten):

In [4]:
m = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

We kunnen de tweede rij in `m` kiezen:

In [3]:
m[1]

[4, 5, 6]

En uit die rij kunnen we het derde element kiezen:

In [4]:
m[1][2]

6

Bovendien, als de sequentie een muteerbare sequentie is, kunnen we een waarde in de sequentie vervangen door een toewijzingsoperator te gebruiken:

In [5]:
m[1][2] = 100
m

[[1, 2, 3], [4, 5, 100], [7, 8, 9]]

NumPy arrays werken ook op deze manier:

In [6]:
import numpy as np

In [7]:
a = np.array([1, 2, 3])

In [8]:
a[0]

1

In [9]:
a[1]

2

In [10]:
a[1] = 200

In [11]:
a

array([  1, 200,   3])

En dit geldt ook voor een 2-D array:

In [12]:
m = np.eye(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
m[1][1]

1.0

In [14]:
m[1][2] = 100

In [15]:
m

array([[  1.,   0.,   0.],
       [  0.,   1., 100.],
       [  0.,   0.,   1.]])

NumPy ondersteunt een iets eenvoudigere syntax voor 2-D (en hoger dimensionale) arrays - in plaats van [ i ][ j ] (en mogelijk [ i ][ j ][ k ] als de dimensies/assen toenemen) te gebruiken, kunnen we gewoon beide indexen, als een tuple, in de [ ] selector specificeren:  

In [16]:
m[(1, 2)]

100.0

In [17]:
m[(1, 1)]

1.0

En ook toewijzing werkt correct op deze wijze:

In [18]:
m[(1, 2)] = 300
m

array([[  1.,   0.,   0.],
       [  0.,   1., 300.],
       [  0.,   0.,   1.]])

Onthoud dat tuples in Python niet altijd omgeven hoeven te worden door `()` - en dat is ook in dit geval zo, wat betekent dat we eenvoudigweg kunnen schrijven:

In [19]:
m[1, 2]

300.0

In [20]:
m[1, 2] = 100
m

array([[  1.,   0.,   0.],
       [  0.,   1., 100.],
       [  0.,   0.,   1.]])

Een laatste punt om te vermelden is dat we moeten onthouden dat NumPy-arrays een vast homogeen type hebben, dus we moeten voorzichtig zijn wanneer we gegevens vervangen om ervoor te zorgen dat deze passen binnen het datatype van de array.

In [21]:
arr = np.array([1, 2, 3, 4], dtype=np.uint8)

Deze array heeft een data type van 8-bit unsigned integers - dus de range van toelaatbare integers is `[0, 255]`.

En als we proberen een element te vervangen door een geheel getal buiten die grenzen, krijgen we het gebruikelijke vreemd gedrag met gehele getallen die 'wrappen':

In [22]:
arr[0] = -100
arr

array([156,   2,   3,   4], dtype=uint8)

In [2]:
import numpy as np
eyematrix = np.eye(5)

In [3]:
eyematrix.dtype

dtype('float64')