### Reshapen van Arrays

Het hervormen van een array stelt ons in staat om de elementen van een array te herordenen - het zijn nog steeds dezelfde elementen, maar gerangschikt in een nieuwe vorm.

In [1]:
import numpy as np

In [2]:
arr = np.arange(12)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr.shape

(12,)

We kunnen deze twaalf elementen tot een 4 x 3 array omvormen:

In [5]:
m1 = arr.reshape(4, 3)
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
m5 = m1.transpose()
m5

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [14]:
m6 = m5.transpose().reshape(12,)
m6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

of naar een 2 x 6 array:

In [6]:
m2 = arr.reshape(2, 6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [7]:
m3 = arr.reshape(2, 2, 3)
m3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

**OPGEPAST** Hervormen wijzigt de originele array niet; de "posities" in beide arrays zijn gedeelde referenties - er wordt verwezen naar dezelfde geheugenadressen.

Dit betekent dat het wijzigen van de elementwaarde in de ene array de elementwaarde in de andere array zal beïnvloeden.

We zullen terugkomen op hoe we elementen van arrays wijzigen, maar we kunnen het doen met behulp van eenvoudige indexering, net zoals we met lijsten hebben gedaan:

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Om de eerste waarde van `arr` te wijzigen:

In [16]:
arr[0] = 100

In [17]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

Zoals we kunnen zien is `arr` gewijzigd, maar kijk eens wat gebeurde met `m1` en `m2`:

In [18]:
m1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [19]:
m2

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

Hetzelfde gebeurt indien we een element van `m1` of `m2` wijzigen:

In [20]:
m1[3][2] = 200

In [21]:
m1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10, 200]])

In [22]:
m2

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10, 200]])

In [23]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200])

Dus, je zou het hervormen (reshapen) moeten beschouwen als een andere "weergave" of "herindeling" van de originele array, **niet** als een volledig onafhankelijke kopie van het origineel.

Later zullen we zien dat zelfs NumPy-slices op dezelfde manier werken.  

Dit is heel anders dan Python-list slices die sliced shallow kopieën teruggeven (ter info: een shallow copy is een kopie waarbij de referenties naar de objecten worden gekopieerd; in Python wordt dus een nieuwe lijst gemaakt die kopieën van de referenties naar de objecten in de oorspronkelijke lijst bevat, maar niet de objecten zelf.  Bij immutable objecten heeft wijziging in de kopie dus geen effect op het origineel.  

Indien we een onafhankelijke kopie willen, dan maken we eenvoudigweg een kopie met behulp van de `copy`methode:

In [24]:
m3 = arr.reshape(3, 4).copy()

In [25]:
m3

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

In [26]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200])

In [27]:
arr[1] = -100

In [28]:
arr

array([ 100, -100,    2,    3,    4,    5,    6,    7,    8,    9,   10,
        200])

In [29]:
m3

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

Zoals je kan zien was `m3` niet gewijzigd.

We kunnen ook een 2-D array naar een 1-D array omvormen met dezelfde `reshape` methode:

In [30]:
m = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

In [31]:
m.shape

(2, 3)

In [32]:
arr2 = m.reshape(6)

In [33]:
arr2

array([1, 2, 3, 4, 5, 6])

Uiteraard geldt ook hier dat de referenties gedeeld zijn:

In [34]:
arr2[2] = 300
arr2

array([  1,   2, 300,   4,   5,   6])

In [35]:
m

array([[  1,   2, 300],
       [  4,   5,   6]])