### Maken van een Array van een list

We moeten eerst `numpy`importeren.

In [1]:
import numpy as np

Het creëren van NumPy-arrays vanuit Python-lijsten is heel eenvoudig - de array functie in NumPy kan een lijst (of een tuple) nemen en er een NumPy-array van maken:

In [2]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array((0.1, 0.2, 0.3, 0.4))

In [3]:
a1

array([1, 2, 3, 4])

In [4]:
a2

array([0.1, 0.2, 0.3, 0.4])

Het data type van deze arrays is `ndarray` (n-dimensional array):

In [5]:
type(a1)

numpy.ndarray

Een van de eigenschappen van een ndarray is zijn datatype (waarvan we weten dat dit het datatype is van elk element in de array)

We hebben geen datatype gespecificeerd voor de elementen van de arrays die we zojuist hebben gemaakt - NumPy koos een standaardwaarde.

We kunnen dit datatype zien door gebruik te maken van de dtype eigenschap:

In [6]:
a1.dtype

dtype('int64')

In [7]:
a2.dtype

dtype('float64')

Zoals je kunt zien koos NumPy int64 en float64 voor onze twee arrays.

We kunnen eigenlijk het datatype van de elementen specificeren als we dat willen - misschien in gevallen waarin we weten dat we geen volledige 64-bits integer of een 64-bits float nodig hebben.

We moeten de NumPy-datatypes gebruiken (die, zoals aangegeven, in principe de onderliggende C-datatypes zijn):

- `np.int8` / `np.uint8`
- `np.int16` / `np.uint16`
- `np.int32` / `np.uint32`
- `np.float32`
- `np.float64`
- etc

In het geval van deze lijst, [1, 2, 3, 4], zouden we eigenlijk kunnen volstaan met unsigned 8-bit integers: 

In [8]:
a = np.array([1, 2, 3, 4], dtype=np.uint8)

En nu zal ons element-datatype unsigned 8-bit integers zijn, wat betekent dat we beperkt zijn tot het bereik [0, 255].  
Wat gebeurt er als we een getal buiten dat bereik gebruiken bij het aanmaken van de array?

In [9]:
a = np.array([1, 2, 3, 300], dtype=np.uint8)

/tmp/ipykernel_89149/258487933.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a = np.array([1, 2, 3, 300], dtype=np.uint8)


In [10]:
a

array([ 1,  2,  3, 44], dtype=uint8)

Zoals je kunt zien, kregen we geen error, en die integer 300 verschijnt als 44 in onze array. Hoe kan dat??

In C, en soortgelijke talen, heeft een integer type een vastgestelde grootte (bijvoorbeeld 8, 16, 32 of 64 bits).

Maximale Waarde: Voor een 8-bit unsigned integer is de maximale waarde 255 (of 11111111 in binaire vorm). Voor een signed integer (met een tekenbit) is de maximale waarde lager.

Overflow: Als je een waarde toevoegt die de maximale capaciteit van de integer overschrijdt, zal er een overflow plaatsvinden. Bijvoorbeeld, als je 1 optelt bij 255 in een 8-bit unsigned integer, zal de waarde 'overstromen'.

Wrap Around: In plaats van een fout te genereren, 'wrapt' de waarde rond naar de laagst mogelijke waarde. In het geval van een 8-bit unsigned integer, zou 255 + 1 resulteren in 0. Het is alsof de teller weer van voor af aan begint.

Bij Signed Integers: Voor signed integers is het proces vergelijkbaar, maar houdt rekening met negatieve waarden. Bijvoorbeeld, een 8-bit signed integer varieert van -128 tot 127. Als je 1 optelt bij 127, 'wrapt' het naar -128.

Dit is beter te zien als volgt:

In [11]:
np.array([255], dtype=np.uint8)

array([255], dtype=uint8)

In [12]:
np.array([256], dtype=np.uint8)

/tmp/ipykernel_89149/2137884065.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.array([256], dtype=np.uint8)


array([0], dtype=uint8)

In [13]:
np.array([257], dtype=np.uint8)

/tmp/ipykernel_89149/1496937367.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 257 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.array([257], dtype=np.uint8)


array([1], dtype=uint8)

Hetzelfde gebeurt met signed integers. Het bereik voor een signed 8-bit integer is [-128, 127]

In [14]:
np.array([127], dtype=np.int8)

array([127], dtype=int8)

In [15]:
np.array([128], dtype=np.int8)

/tmp/ipykernel_89149/520780534.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.array([128], dtype=np.int8)


array([-128], dtype=int8)

In [16]:
np.array([129], dtype=np.int8)

/tmp/ipykernel_89149/961925688.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.array([129], dtype=np.int8)


array([-127], dtype=int8)

Dus zoals je kunt zien, 'wrappen' deze ook.

-> wees voorzichtig en zorg ervoor dat je geen type gebruikt dat te beperkend is als je ervoor kiest om het type expliciet te specificeren.

Waarom laten we NumPy niet altijd gewoon het type voor ons specificeren (wat int64 en float64 was)?

Omwille van opslagefficiëntie - denk 64 bits geheugen versus 8 bits vereist. Wanneer je slechts een paar getallen hebt, is het verschil verwaarloosbaar - maar wanneer je begint te werken met zeer grote datasets, kan het een groot verschil maken.

Onthoud wat we eerder zagen - NumPy-arrays zijn homogeen - d.w.z. alle elementen moeten van hetzelfde type zijn, in tegenstelling tot Python-lists.

In [17]:
a = np.array([1, 2, 3.14])

In [18]:
a

array([1.  , 2.  , 3.14])

In [19]:
a.dtype

dtype('float64')

Zoals je kunt zien, koos NumPy voor een float type, aangezien een van de getallen in de lijst een float was.

We kunnen dit natuurlijk overschrijven door het type te specificeren dat we willen, maar mogelijk met wat dataverlies als gevolg:

In [20]:
np.array([1, 2, 9.9, 9.1], dtype=np.int64)

array([1, 2, 9, 9])

Zoals je kunt zien, verliezen de floats de cijfers na de komma.

#### Multi-Dimensionale Arrays

Je hebt meerdimensionale lists in Python - in principe lijsten die andere lijsten bevatten.

Deze nesting kan tot elke diepte voorkomen, maar hier houden we het bij 2-dimensionale arrays (matrices). Hogere dimensies werken op dezelfde manier, maar zijn moeilijker te begrijpen.

Een voorbeeld:

In [21]:
m_py = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

Dit is een 2-dimensionale lijst - de buitenste lijst is een lijst van elementen, waarbij elk element opnieuw een lijst is.

We kunnen hier denken in termen van rijen en kolommen - in dit geval hebben we drie rijen en drie kolommen.

We zouden in Python een onregelmatige lijst kunnen maken (waar niet elke rij hetzelfde aantal elementen bevat), maar dit werkt niet echt met NumPy-arrays waar elke rij hetzelfde aantal kolommen heeft.  

We kunnen deze Python 2-dimensionale list transformeren naar een 2-dimensionale array:

In [22]:
m1 = np.array(m_py, dtype=np.int8)

In [23]:
m1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

Opnieuw is de hele array homogeen - dus alle elementen zijn in dit geval 8-bit signed integers.

**Array Eigenschappen**  

Deze ndarray-objecten hebben bepaalde eigenschappen, waarvan we de dtype-eigenschap al hebben gezien.

Er is ook een eigenschap om het totale aantal elementen in de array te krijgen:

In [24]:
a = np.array([1, 2, 3])
m2 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ]
)

In [25]:
a

array([1, 2, 3])

In [26]:
m1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [27]:
m2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
a.size

3

In [29]:
m1.size

9

In [30]:
m2.size

12

arrays hebben ook een bepaalde 'vorm':
- `a`: 1 rij, 3 kolommen (kan worden beschouwd als een rijvector)
- `m1`: 3 rijen, 3 kolommen
- `m2`: 4 rijen, 3 kolommen  

Dit is informatie die de shape-eigenschap van een ndarray ons kan vertellen:

In [31]:
a.shape

(3,)

In [32]:
m1.shape

(3, 3)

In [33]:
m2.shape

(4, 3)

Zoals we kunnen zien, geeft shape een tuple terug met evenveel dimensies als de array heeft, waarbij ook de grootte in elke dimensie wordt weergegeven.

a is een 1-D array, dus slechts 1 element werd geretourneerd in de shape-tuple (en het weergevenen getal is het aantal elementen in die dimensie), terwijl m1 en m2 2-D arrays waren, dus zien we twee getallen in de shape-tuple.